### ISSUE TITLE
Ambiente Windows - Problemas ao executar projeto

### ISSUE THREAD

**Issue by luanmarques1789** [wchagas/pagseguro-react#15]
Olá, **@wchagas**, eu estou com problemas em rodar o seu projeto.

Primeiramente, a aplicação seria a sua **API pagseguro-react**? Esse ponto não compreendi muito bem no README.

Ademais, vamos para o problema.
Quando eu executei o comando _npm run dev_, apareceu o seguinte erro:

![run-failed](https://user-images.githubusercontent.com/49290580/118534359-83eabb80-b71f-11eb-9443-07b9ac29f64e.PNG)

**PS.:** 
- Eu estou executando o fork do projeto original;
- 1º instalei as dependencies e dev dependencies;
- 2º instalei as peer dependencies manualmente.

**Comment by wanderlima** [comment]
@luanmarques1789 

Seu ambiente é Windows?

**Comment by luanmarques1789** [comment]
> @luanmarques1789
> 
> Seu ambiente é Windows?

Sim!

**Comment by wanderlima** [comment]
ok

O **NODE_ENV** do script **dev** não vai funcionar no seu ambiente:

```
"dev": "NODE_ENV=development webpack-dev-server"
```

Tente alterar para:

```
"dev": "SET NODE_ENV=development & webpack-dev-server"
```

**Comment by luanmarques1789** [comment]
**Funcionou!** Muito obrigado!

![run-success](https://user-images.githubusercontent.com/49290580/118678826-be159500-b7d3-11eb-9d96-0a14e88a896d.PNG)
