### ISSUE TITLE
exclude nao funciona

### ISSUE THREAD

**Issue by ernaneluis** [wchagas/pagseguro-react#5]
parece que o exclude estar para TODO, confirma?  https://github.com/wchagas/pagseguro-react/blob/3142ff92fc055696ff40e38ab948562b23f9e32d/src/config.js#L33

Gostaria de excluir Boleto e de debito.

**Comment by wchagas** [comment]
Atualmente você pode remover o  boleto e débito. Tente:

https://github.com/wchagas/pagseguro-react/blob/master/example/Component/DirectPayment/index.js#L269

```
exclude={[
	'ONLINE_DEBIT',
	'BOLETO'
]}
```

**Comment by ernaneluis** [comment]
<img width="795" alt="Screenshot 2019-08-19 at 20 55 23" src="https://user-images.githubusercontent.com/1398769/63307142-b30e9780-c2c3-11e9-9cbc-aa8bcae53bb9.png">
nao funciona

**Comment by ernaneluis** [comment]
consegui! desculpa fiz errado

**Comment by wchagas** [comment]
Tranquilo, qualquer coisa chama.
