### ISSUE TITLE
Problemas ao entrar na aba de pagamentos

### ISSUE THREAD

**Issue by muriloneo** [wchagas/pagseguro-react#8]
Instalei, gerei a session, atualizei state. OK.

passei as abas até a de pagamento e então falha uma requisição:

https://ws.sandbox.pagseguro.uol.com.br/payment-methods?callback=callbackPaymentMethods&sessionId=<SESSIONID>&amount=124.00&Accept=application/vnd.pagseguro.com.br.v1%2Bjson;charset=ISO-8859-1

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Sep 09 13:06:15 BRT 2019
There was an unexpected error (type=Internal Server Error, status=500).
Invalid character '=' for QUERY_PARAM in "application/vnd.pagseguro.com.br.v1%2Bjson;charset=ISO-8859-1"

**Comment by wchagas** [comment]
Esse erro é gerado pelo do Pagseguro, infelizmente não tenho muito o que fazer. Podemos entrar em contato com o suporte e informar o erro. 

O erro ocorre porque estão passando o Accept como query, ai quebra por causa do sinal (=): charset=ISO-8859-1 deveria ser charset%2ISO-8859-1.

Se puder ajudar dá um toque pra eles.

**Comment by muriloneo** [comment]
Eu não estou usando o projeto do backend, inicio a sessão de outra forma. Pode ser esse o problema que o componente não está funcionando?

Se eu rodar o exemplo, react + node, deveria funcionar ou está travado nesse erro mesmo?

**Comment by wchagas** [comment]
O pagseguro disponibiliza uma lib (https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js) e é ela que faz esse request que está com erro (Eu a importo dinamicamente no load do componente). Não tem relação com seu backend, se você está passando a session, então, deveria funcionar, mas o erro é com eles mesmo :(

O ambiente sandbox do Pagseguro é instável, tenho certeza que eles tem uma ótima equipe, mas o projeto deve ser legado. O fato é que a gente depende dos caras. 

Não tive tempo pra comunicar o pessoal, se puder publica o erro no forum e anexa o link dessa Issue, talvez os ajude.

Se quiser você pode conferir o bug fazendo um request pra página de erro (reforçando: Esse request é feito pela lib do pagseguro (client) e portanto não temos como alterar a requisição). 

Erro: https://ws.sandbox.pagseguro.uol.com.br/payment-methods?callback=callbackPaymentMethods&sessionId={SUA_SESSION_AQUI}&amount=124.00&Accept=application/vnd.pagseguro.com.br.v1%2Bjson;charset=ISO-8859-1

Sucesso: https://ws.sandbox.pagseguro.uol.com.br/payment-methods?callback=callbackPaymentMethods&sessionId={SUA_SESSION_AQUI}&amount=124.00&Accept=application/vnd.pagseguro.com.br.v1%2Bjson;charset%3DISO-8859-1

**Comment by icorradi** [comment]
Estou com o mesmo problema =(

**Comment by wchagas** [comment]
Comuniquei a equipe via central de atendimento, a página da comunidade está fora (https://comunidade.pagseguro.uol.com.br/hc/pt-br/community/topics?_ga=2.27218622.2092699934.1568129124-436187697.1561142238)

Assim que tiver retorno aviso por aqui.

**Comment by wchagas** [comment]
Ainda não responderam! @muriloneo você cadastrou umas issues, não está mais com este problema?

**Comment by muriloneo** [comment]
O problema está só em sandbox. Como a integração que estou implementando ainda não está ativa eu estou testando em produção. Infelizmente. 
Entrei em contato com eles também e me disseram que estao reformulando lá, também abri um chamado e não responderam.

**Comment by samucawebdesign** [comment]
Mesma coisa aqui, só funciona em produção. No sandbox dá erro 500 somente com pagamento via cartão

**Comment by muriloSanto** [comment]
Pagseguro acabou de entrar em contato comigo dizendo que corrigiram o problema. Só para informar a todos!

Pra mim agora está dando outro problema, mas deve ser na criação da session.

**Comment by muriloneo** [comment]
Pagseguro acabou de entrar em contato comigo dizendo que corrigiram o problema. Só para informar a todos!

Pra mim agora está dando outro problema, mas deve ser na criação da session.

**Comment by samucawebdesign** [comment]
Realmente, testei aqui e tudo funcionando agora, valeu pessoal! =D

**Comment by wchagas** [comment]
Opa, funcionando? Beleza.

@muriloneo vou dar uma olhada nas issues, mas fique a vontade pra fazer as alterações, estou ocupado agora, sua ajuda será muito bem vinda. Inclusive futuramente pretendo refatorar e adicionar suporte pra react-native, se estiverem disponíveis e puderem contribuir será ótimo.
