### ISSUE TITLE
Uso de componentWillMount deprecated

### ISSUE THREAD

**Issue by muriloneo** [wchagas/pagseguro-react#9]
https://github.com/wchagas/pagseguro-react/blob/33b207e9b9fda9d39940d87c4299097a99f2336b/src/DirectPayment/Forms/Payment.js

**Comment by wchagas** [comment]
Futuramente irei implementar Hooks, porém, no momento pretendo manter essa versão. Vou adicionar UNSAFE_ para remover os consoles irritantes.
